# Generated by Django 2.2.13 on 2020-07-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='usser',
            new_name='user',
        ),
    ]
